name: Grading

on: [push, pull_request]

jobs:
  build_and_grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile the code
        run: gcc -o main main.c

      - name: Test Case 1: Correct password on first try
        run: |
          echo "2025" | ./main | grep -q "Log-In success!"
          if [ $? -eq 0 ]; then
            echo "Test 1 Passed"
          else
            echo "Test 1 Failed"
            exit 1
          fi

      - name: Test Case 2: Correct password on third try
        run: |
          echo -e "1111\n2222\n2025" | ./main | grep -q "Log-In success!"
          if [ $? -eq 0 ]; then
            echo "Test 2 Passed"
          else
            echo "Test 2 Failed"
            exit 1
          fi

      - name: Test Case 3: Failed all 5 tries
        run: |
          echo -e "1\n2\n3\n4\n5" | ./main | grep -q "Log-In Failed"
          if [ $? -eq 0 ]; then
            echo "Test 3 Passed"
          else
            echo "Test 3 Failed"
            exit 1
          fi
